const COLORS = {
  GHOST_WHITE: 'rgba(250, 251, 255, 1)',
  AZUREISH_WHITE: 'rgba(226,232,240,0.8)',
  YANKEES_BLUE: 'rgba(31, 41, 55, 1)',
  EERIE_BLACK: 'rgba(17, 24, 39, 1)',
  ULTRAMARINE: `rgba(52, 102, 246, 1)`,
  BLACK: 'rgba(0, 0, 0, 1)',
  WHITE: 'rgba(255, 255, 255, 1)',
  GREY: 'rgba(229, 231, 235, 0.5)',
  METAL: 'rgba(107, 114, 128, 1)',
  BRIGHT_GREY: 'rgba(229, 231, 235, 1)',
  SKY_BLUE: 'rgba(147, 197, 253, 1)',
};

const LIGHT_THEME = {
  BACKGROUND: COLORS.GHOST_WHITE,
  BASE: COLORS.WHITE,
  BORDER: COLORS.AZUREISH_WHITE,
  TEXT: COLORS.BLACK,
  BUTTON: COLORS.ULTRAMARINE,
  BUTTON_TEXT: COLORS.WHITE,
  ICON: COLORS.GREY,
  ACTIVITY: COLORS.METAL,
  ACTIVITY_BORDER: COLORS.SKY_BLUE,
};

const DARK_THEME = {
  BACKGROUND: COLORS.BLACK,
  BASE: COLORS.EERIE_BLACK,
  BORDER: COLORS.YANKEES_BLUE,
  TEXT: COLORS.WHITE,
  BUTTON: COLORS.ULTRAMARINE,
  BUTTON_TEXT: COLORS.WHITE,
  ICON: COLORS.GREY,
  ACTIVITY: COLORS.BRIGHT_GREY,
  ACTIVITY_BORDER: COLORS.SKY_BLUE,
};

export { LIGHT_THEME, DARK_THEME };
